name: Testing
on: [push, pull_request]
jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Verificar repositorio
        uses: actions/checkout@v2

      - name: Instalar Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar ESLint
        run: npm run lint
